#!/bin/bash
set -euo pipefail

if [ "$(whoami)" != "root" ]; then
    echo "must be run with sudo"
    exit 1
fi

TIMELIMIT_PLIST_FILE="/Library/LaunchDaemons/com.timelimit.pf.plist"

TIMELIMIT_ANCHOR="/etc/pf.anchors/timelimit"
SCHEDULE_RULES="/etc/pf.anchors/timelimit.schedule"
SERVICES_RULES="/etc/pf.anchors/timelimit.services"

cat > "$TIMELIMIT_PLIST_FILE" <<'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
 "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.timelimit.pf</string>

  <key>ProgramArguments</key>
  <array>
    <string>/sbin/pfctl</string>
    <string>-e</string>
  </array>

  <key>RunAtLoad</key>
  <true/>
</dict>
</plist>
EOF

chown root:wheel "$TIMELIMIT_PLIST_FILE"
chmod 644 "$TIMELIMIT_PLIST_FILE"

launchctl bootout system "$TIMELIMIT_PLIST_FILE" 2>/dev/null || true
launchctl bootstrap system "$TIMELIMIT_PLIST_FILE"
launchctl enable system/com.timelimit.pf

grep -q '^anchor "timelimit"$' /etc/pf.conf || echo 'anchor "timelimit"' >> /etc/pf.conf
grep -q '^load anchor "timelimit" from "/etc/pf.anchors/timelimit"$' /etc/pf.conf || echo 'load anchor "timelimit" from "/etc/pf.anchors/timelimit"' >> /etc/pf.conf

cat > "$TIMELIMIT_ANCHOR" <<'EOF'
anchor "schedule"
load anchor "schedule" from "/etc/pf.anchors/timelimit.schedule"

anchor "services"
load anchor "services" from "/etc/pf.anchors/timelimit.services"
EOF

cat > "$SCHEDULE_RULES" <<'EOF'
# autogenerated by update_access.sh
# internet permitted by schedule
EOF

cat > "$SERVICES_RULES" <<'EOF'
# autogenerated by update_access.sh
# no services blocked
EOF

chown root:wheel "$TIMELIMIT_ANCHOR" "$SCHEDULE_RULES" "$SERVICES_RULES"
chmod 644 "$TIMELIMIT_ANCHOR" "$SCHEDULE_RULES" "$SERVICES_RULES"

pfctl -vnf /etc/pf.conf
pfctl -f /etc/pf.conf
pfctl -e 2>/dev/null || true
