#!/bin/bash
set -euo pipefail

if [ "$(whoami)" != "root" ]; then
    echo "must be run with sudo"
    exit 1
fi

TIMELIMIT_PLIST_FILE="/Library/LaunchDaemons/com.timelimit.pf.plist"

cat > "$TIMELIMIT_PLIST_FILE" <<'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
 "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.timelimit.pf</string>

  <key>ProgramArguments</key>
  <array>
    <string>/sbin/pfctl</string>
    <string>-e</string>
  </array>

  <key>RunAtLoad</key>
  <true/>
</dict>
</plist>
EOF

chown root:wheel "$TIMELIMIT_PLIST_FILE"
chmod 644 "$TIMELIMIT_PLIST_FILE"

launchctl bootout system "$TIMELIMIT_PLIST_FILE" 2>/dev/null || true
launchctl bootstrap system "$TIMELIMIT_PLIST_FILE"
launchctl enable system/com.timelimit.pf

grep -q '^anchor "timelimit"$' /etc/pf.conf || echo 'anchor "timelimit"' >> /etc/pf.conf

grep -q '^load anchor "timelimit" from "/etc/pf.anchors/timelimit"$' /etc/pf.conf || echo 'load anchor "timelimit" from "/etc/pf.anchors/timelimit"' >> /etc/pf.conf

cat > /etc/pf.anchors/timelimit <<'EOF'
# autogenerated rules will be written here by update_access.sh
EOF

pfctl -vnf /etc/pf.conf
pfctl -f /etc/pf.conf
pfctl -e 2>/dev/null || true
