#!/bin/bash
set -euo pipefail

LOGIN_USER=$(stat -f '%Su' /dev/console)

THRESHOLD=1
ANCHOR="/etc/pf.anchors/timelimit"
QUOTAS="/Users/$LOGIN_USER/.activity_logger/current_quotas.txt"
TMP="$(mktemp)"

trap 'rm -f "$TMP"' EXIT

youtube_domains="youtube.com, www.youtube.com, youtu.be"
discord_domains="discord.com, discord.gg"
gaming_domains="roblox.com, www.roblox.com"

write_rules() {
    local domains="$1"

    cat > "$TMP" <<EOF
# autogenerated by update_access.sh

table <blocked> persist { $domains }

block drop out quick proto tcp to <blocked> port { 80 443 }
block drop out quick proto udp to <blocked> port 443
EOF

    cp "$TMP" "$ANCHOR"
    /sbin/pfctl -a timelimit -f "$ANCHOR"
    /sbin/pfctl -F states >/dev/null 2>&1 || true
}

fail_closed() {
    write_rules "$youtube_domains, $discord_domains, $gaming_domains"
    exit 1
}

[ -r "$QUOTAS" ] || fail_closed

blocked_domains=""

add_domains() {
    if [ -z "$blocked_domains" ]; then
        blocked_domains="$1"
    else
        blocked_domains="$blocked_domains, $1"
    fi
}

{
    while read -r service quota; do
        block=$(awk -v q="$quota" -v t="$THRESHOLD" 'BEGIN { print (q < t) ? 1 : 0 }')
        [ "$block" -eq 1 ] || continue

        case "$service" in
            youtube) add_domains "$youtube_domains" ;;
            discord) add_domains "$discord_domains" ;;
            gaming)  add_domains "$gaming_domains" ;;
            *) continue ;;
        esac
    done < "$QUOTAS"
} || fail_closed

if [ -z "$blocked_domains" ]; then
    cat > "$TMP" <<EOF
# autogenerated by update_access.sh
# no services blocked
EOF
    cp "$TMP" "$ANCHOR"
    /sbin/pfctl -a timelimit -f "$ANCHOR"
else
    write_rules "$blocked_domains"
fi
