#!/bin/bash
set -euo pipefail

LOGIN_USER=$(stat -f '%Su' /dev/console)

THRESHOLD=1

SCHEDULE_ANCHOR="timelimit/schedule"
SERVICES_ANCHOR="timelimit/services"

SCHEDULE_RULES="/etc/pf.anchors/timelimit.schedule"
SERVICES_RULES="/etc/pf.anchors/timelimit.services"

QUOTAS="/Users/$LOGIN_USER/.activity_logger/current_quotas.txt"

TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

TMP_SCHEDULE="$TMPDIR/schedule"
TMP_SERVICES="$TMPDIR/services"

youtube_domains="youtube.com, www.youtube.com, youtu.be"
discord_domains="discord.com, discord.gg"
gaming_domains="roblox.com, www.roblox.com"


# Convert "21:30" to minutes since midnight.
mins() {
    H=${1%:*}
    M=${1#*:}

    echo $((60 * 10#$H + 10#$M))
}


# Replace one anchor without touching the other anchor.
# Return success when the rules changed.
load_if_changed() {
    local anchor="$1"
    local source="$2"
    local installed="$3"

    if [ -r "$installed" ] && cmp -s "$source" "$installed"; then
        return 1
    fi

    /sbin/pfctl -a "$anchor" -f "$source"
    cp "$source" "$installed"

    return 0
}


flush_states() {
    /sbin/pfctl -F states >/dev/null 2>&1 || true
}


enable_night_block() {
    cat > "$TMP_SCHEDULE" <<EOF
# autogenerated by update_access.sh
# internet blocked outside permitted hours

block drop out quick all
EOF

    if load_if_changed \
        "$SCHEDULE_ANCHOR" \
        "$TMP_SCHEDULE" \
        "$SCHEDULE_RULES"
    then
        flush_states
    fi
}


disable_night_block() {
    cat > "$TMP_SCHEDULE" <<EOF
# autogenerated by update_access.sh
# internet permitted by schedule
EOF

    load_if_changed \
        "$SCHEDULE_ANCHOR" \
        "$TMP_SCHEDULE" \
        "$SCHEDULE_RULES" || true
}


write_service_rules() {
    local domains="$1"

    if [ -z "$domains" ]; then
        cat > "$TMP_SERVICES" <<EOF
# autogenerated by update_access.sh
# no services blocked
EOF
    else
        cat > "$TMP_SERVICES" <<EOF
# autogenerated by update_access.sh

table <blocked> persist { $domains }

block drop out quick proto tcp to <blocked> port { 80 443 }
block drop out quick proto udp to <blocked> port 443
EOF
    fi

    if load_if_changed \
        "$SERVICES_ANCHOR" \
        "$TMP_SERVICES" \
        "$SERVICES_RULES"
    then
        flush_states
    fi
}


fail_closed() {
    write_service_rules \
        "$youtube_domains, $discord_domains, $gaming_domains"

    exit 1
}


# Check whether internet access is permitted by the schedule.
now=$(date "+%H:%M")
weekday=$(date "+%u")

starttime="06:00"

case "$weekday" in
    5 | 6) stoptime="22:30" ;;
        *) stoptime="21:30" ;;
esac

x=$(mins "$now")
x0=$(mins "$starttime")
x1=$(mins "$stoptime")

if [[ $x -lt $x0 || $x -ge $x1 ]]; then
    enable_night_block
    exit 0
fi


# Remove the night rule before resolving service hostnames.
disable_night_block


# Apply quota-controlled service rules.
[ -r "$QUOTAS" ] || fail_closed

blocked_domains=""

add_domains() {
    if [ -z "$blocked_domains" ]; then
        blocked_domains="$1"
    else
        blocked_domains="$blocked_domains, $1"
    fi
}

while read -r service quota; do
    if ! block=$(awk -v q="$quota" -v t="$THRESHOLD" \
        'BEGIN { print (q < t) ? 1 : 0 }')
    then
        fail_closed
    fi

    [ "$block" -eq 1 ] || continue

    case "$service" in
        youtube) add_domains "$youtube_domains" ;;
        discord) add_domains "$discord_domains" ;;
        gaming)  add_domains "$gaming_domains" ;;
        *)        continue ;;
    esac
done < "$QUOTAS"

write_service_rules "$blocked_domains"
