#!/bin/bash
set -euo pipefail

cd "$(dirname "$0")"

THRESHOLD=1
ANCHOR="/etc/pf.anchors/timelimit"
QUOTAS="current_quotas.json"
TMP="$(mktemp)"

youtube_domains="youtube.com www.youtube.com youtu.be googlevideo.com ytimg.com"
discord_domains="discord.com discord.gg discordapp.com discordapp.net"
gaming_domains="roblox.com www.roblox.com api.roblox.com games.roblox.com gamejoin.roblox.com assetgame.roblox.com setup.roblox.com clientsettings.roblox.com catalog.roblox.com economy.roblox.com thumbnails.roblox.com images.rbxcdn.com rbxcdn.com www.rbxcdn.com cdn.roblox.com"

{
    echo "# autogenerated by activity_logger/update_access.sh"
    echo
} > "$TMP"

[ -f "$QUOTAS" ] || echo '{}' > "$QUOTAS"

jq -r 'to_entries | sort_by(.key)[] | "\(.key) \(.value)"' "$QUOTAS" |
while read -r service quota; do
    block=$(awk -v q="$quota" -v t="$THRESHOLD" 'BEGIN { print (q < t) ? 1 : 0 }')
    [ "$block" -eq 1 ] || continue

    case "$service" in
        youtube) domains="$youtube_domains" ;;
        discord) domains="$discord_domains" ;;
        gaming)  domains="$gaming_domains" ;;
        *) continue ;;
    esac

    echo "table <${service}_blocked> persist { $domains }"
    echo "block drop out quick proto tcp to <${service}_blocked> port { 80 443 }"
    echo "block drop out quick proto udp to <${service}_blocked> port 443"
    echo
done >> "$TMP"

cp "$TMP" "$ANCHOR"
rm "$TMP"

/sbin/pfctl -a timelimit -f "$ANCHOR" 2>/dev/null
